export const hits = [
    {
      avgLearningHours: null,
      tagline: null,
      name: 'IBM Data Science',
      partnerLogos: [
        'http://coursera-university-assets.s3.amazonaws.com/bb/f5ced2bdd4437aa79f00eb1bf7fbf0/IBM-Logo-Blk---Square.png'
      ],
      isPartOfCourseraPlus: false,
      subtitleLanguage: [
        'Arabic',
        'Chinese (China)',
        'French',
        'German',
        'Italian',
        'Korean',
        'Persian',
        'Portuguese (Portugal)',
        'Russian',
        'Spanish',
        'Turkish',
        'Vietnamese'
      ],
      productDifficultyLevel: 'Beginner',
      audience: null,
      enrollments: 720172,
      partners: [ 'IBM' ],
      language: 'English',
      entityType: 'PROFESSIONAL CERTIFICATE',
      numProductRatings: 67939,
      allLanguageCodes: [
        'ar', 'zh', 'en',
        'fr', 'de', 'it',
        'ko', 'fa', 'pt',
        'ru', 'es', 'tr',
        'vi'
      ],
      avgProductRating: 4.612835043200519,
      skills: [
        'Algorithms',
        'Computer Programming',
        'Data Analysis',
        'Data Visualization',
        'Machine Learning',
        'Python Programming',
        'Sql',
        'Analysis',
        'Ipython',
        'Methodology'
      ],
      imageUrl: 'https://d15cw65ipctsrr.cloudfront.net/23/22bc54f77f45a2b057f4ff518d272f/iStock-1169539468.jpg',
      isCourseFree: false,
      objectUrl: '/professional-certificates/ibm-data-science',
      objectID: 's12n~dwzq23ZLEei12goo904QNg',
      _snippetResult: { description: [Object] },
      _highlightResult: { name: [Object] }
    },
    {
      avgLearningHours: null,
      tagline: null,
      name: 'Google IT Support',
      partnerLogos: [
        'http://coursera-university-assets.s3.amazonaws.com/b6/a7ddd772194a22b3e8e8cb27d29702/500x500_Google.png'
      ],
      isPartOfCourseraPlus: true,
      subtitleLanguage: [
        'Arabic',
        'Chinese (China)',
        'French',
        'German',
        'Italian',
        'Korean',
        'Portuguese (Brazil)',
        'Portuguese (Portugal)',
        'Russian',
        'Spanish',
        'Turkish',
        'Vietnamese'
      ],
      productDifficultyLevel: 'Beginner',
      audience: null,
      enrollments: 758746,
      partners: [ 'Google' ],
      language: 'English',
      entityType: 'PROFESSIONAL CERTIFICATE',
      numProductRatings: 80869,
      allLanguageCodes: [
        'ar', 'zh', 'en',
        'fr', 'de', 'it',
        'ko', 'pt', 'ru',
        'es', 'tr', 'vi'
      ],
      avgProductRating: 4.773667289072453,
      skills: [
        'Computer Networking',
        'Network Security',
        'Backup',
        'Directory Services',
        'File System',
        'Linux File Systems',
        'Modeling',
        'Powershell',
        'Security',
        'Software'
      ],
      imageUrl: 'https://d15cw65ipctsrr.cloudfront.net/14/b2d530f1ad11e7ab380fc0c6c817a8/Search-Thumbnail.jpg',
      isCourseFree: false,
      objectUrl: '/professional-certificates/google-it-support',
      objectID: 's12n~7lHCSlFIEeeffRIHljDI_g',
      _snippetResult: { description: [Object] },
      _highlightResult: { name: [Object] }
    },
    {
      avgLearningHours: null,
      tagline: 'Become a Deep Learning experts\nOffered by DeepLearning.AI',
      name: 'Deep Learning',
      partnerLogos: [
        'http://coursera-university-assets.s3.amazonaws.com/2b/054650300011e9adc895106b89a651/GreyLogoName360x360.png'
      ],
      isPartOfCourseraPlus: false,
      subtitleLanguage: [
        'Arabic',
        'Chinese (China)',
        'Chinese (Traditional)',
        'French',
        'German',
        'Italian',
        'Japanese',
        'Korean',
        'Portuguese (Brazil)',
        'Portuguese (Portugal)',
        'Russian',
        'Spanish',
        'Turkish',
        'Ukrainian',
        'Vietnamese'
      ],
      productDifficultyLevel: 'Intermediate',
      audience: null,
      enrollments: 984000,
      partners: [ 'DeepLearning.AI' ],
      language: 'English',
      entityType: 'SPECIALIZATION',
      numProductRatings: 116643,
      allLanguageCodes: [
        'ar', 'zh', 'en',
        'fr', 'de', 'it',
        'ja', 'ko', 'pt',
        'ru', 'es', 'tr',
        'uk', 'vi'
      ],
      avgProductRating: 4.841637303567299,
      skills: [
        'Artificial Neural Networks',
        'Convolutional Neural Network',
        'Deep Learning',
        'Human Learning',
        'Hyperparameter Optimization',
        'Long Short-Term Memory',
        'Tensorflow',
        'Face Recognition',
        'Hyperparameter',
        'Mathematical Optimization'
      ],
      imageUrl: 'https://d15cw65ipctsrr.cloudfront.net/57/4be3fd8d16487ab9cfa7bba909b236/GreyLogoName1000x1000.png',
      isCourseFree: false,
      objectUrl: '/specializations/deep-learning',
      objectID: 's12n~W62RsyrdEeeFQQqyuQaohA',
      _snippetResult: { description: [Object] },
      _highlightResult: { name: [Object] }
    },
    {
      avgLearningHours: null,
      tagline: null,
      name: 'IBM Data Analyst',
      partnerLogos: [
        'http://coursera-university-assets.s3.amazonaws.com/bb/f5ced2bdd4437aa79f00eb1bf7fbf0/IBM-Logo-Blk---Square.png'
      ],
      isPartOfCourseraPlus: false,
      subtitleLanguage: [
        'Arabic',
        'Chinese (China)',
        'French',
        'German',
        'Italian',
        'Korean',
        'Persian',
        'Portuguese (Portugal)',
        'Russian',
        'Spanish',
        'Turkish',
        'Vietnamese'
      ],
      productDifficultyLevel: 'Beginner',
      audience: null,
      enrollments: 417122,
      partners: [ 'IBM' ],
      language: 'English',
      entityType: 'PROFESSIONAL CERTIFICATE',
      numProductRatings: 31308,
      allLanguageCodes: [
        'ar', 'zh', 'en',
        'fr', 'de', 'it',
        'ko', 'fa', 'pt',
        'ru', 'es', 'tr',
        'vi'
      ],
      avgProductRating: 4.608675099016229,
      skills: [
        'Computer Programming',
        'Data Analysis',
        'Data Visualization',
        'Databases',
        'Financial Analysis',
        'Matplotlib',
        'Microsoft Excel',
        'Python Programming',
        'Sql',
        'Analysis'
      ],
      imageUrl: 'https://d15cw65ipctsrr.cloudfront.net/63/baf9bea98641aeb8fd36a7b1291791/DA-PC_Image.jpg',
      isCourseFree: false,
      objectUrl: '/professional-certificates/ibm-data-analyst',
      objectID: 's12n~7qRy6fOWEeqIvgrCa-MVgQ',
      _snippetResult: { description: [Object] },
      _highlightResult: { name: [Object] }
    },
    {
      avgLearningHours: null,
      tagline: 'Launch your career in data science\nOffered by IBM',
      name: 'Introduction to Data Science',
      partnerLogos: [
        'http://coursera-university-assets.s3.amazonaws.com/bb/f5ced2bdd4437aa79f00eb1bf7fbf0/IBM-Logo-Blk---Square.png'
      ],
      isPartOfCourseraPlus: false,
      subtitleLanguage: [
        'Arabic',
        'Chinese (China)',
        'French',
        'German',
        'Italian',
        'Korean',
        'Persian',
        'Portuguese (Portugal)',
        'Russian',
        'Spanish',
        'Turkish',
        'Vietnamese'
      ],
      productDifficultyLevel: 'Beginner',
      audience: null,
      enrollments: 469238,
      partners: [ 'IBM' ],
      language: 'English',
      entityType: 'SPECIALIZATION',
      numProductRatings: 52081,
      allLanguageCodes: [
        'ar', 'zh', 'en',
        'fr', 'de', 'it',
        'ko', 'fa', 'pt',
        'ru', 'es', 'tr',
        'vi'
      ],
      avgProductRating: 4.620433555423285,
      skills: [
        'Computer Programming',
        'Data Model',
        'Databases',
        'Python Programming',
        'Sql',
        'Ibm Db2',
        'Ipython',
        'Methodology',
        'Modeling',
        'Rstudio'
      ],
      imageUrl: 'https://d15cw65ipctsrr.cloudfront.net/32/d719a2d0d946d59e1151bc10ec29f5/Specialization-Certificate-Emblem---IDS---600x600.png',
      isCourseFree: false,
      objectUrl: '/specializations/introduction-data-science',
      objectID: 's12n~_Fk2Gi3cEeiHghIydZ_0lA',
      _snippetResult: { description: [Object] },
      _highlightResult: { name: [Object] }
    },
    {
      avgLearningHours: 56,
      tagline: 'Offered by Stanford University',
      name: 'Machine Learning',
      partnerLogos: [
        'http://coursera-university-assets.s3.amazonaws.com/e8/7cc3d09d3f11e698dfff46d35f2da1/Stanford_Coursera_Logo.png'
      ],
      isPartOfCourseraPlus: false,
      subtitleLanguage: [
        'Chinese (China)',
        'Italian',
        'Japanese',
        'Korean',
        'French',
        'Vietnamese',
        'Portuguese (Portugal)',
        'Hebrew',
        'Turkish',
        'Russian',
        'German',
        'Arabic',
        'Hindi',
        'Spanish'
      ],
      productDifficultyLevel: 'Mixed',
      audience: null,
      enrollments: 3871638,
      partners: [ 'Stanford University' ],
      language: 'English',
      entityType: 'COURSE',
      numProductRatings: 153955,
      allLanguageCodes: [
        'zh', 'it', 'ja', 'ko',
        'fr', 'vi', 'pt', 'he',
        'tr', 'ru', 'de', 'ar',
        'hi', 'es', 'en'
      ],
      avgProductRating: 4.91422168815563,
      skills: [
        'Artificial Neural Networks',
        'Logistic Regression',
        'Regression',
        'Linear Regression',
        'Algorithms',
        'Linearity',
        'Supply Chain',
        'Support Vector Machine',
        'Human Learning',
        'Machine Learning'
      ],
      imageUrl: 'https://s3.amazonaws.com/coursera/topics/ml/large-icon.png',
      isCourseFree: true,
      objectUrl: '/learn/machine-learning',
      objectID: 'course~Gtv4Xb1-EeS-ViIACwYKVQ',
      _snippetResult: { description: [Object] },
      _highlightResult: { name: [Object] }
    },
    {
      avgLearningHours: null,
      tagline: 'Learn to Program and Analyze Data with Python\n' +
        'Offered by University of Michigan',
      name: 'Python for Everybody',
      partnerLogos: [
        'https://coursera-university-assets.s3.amazonaws.com/70/de505d47be7d3a063b51b6f856a6e2/New-Block-M-Stacked-Blue-295C_600x600.png'
      ],
      isPartOfCourseraPlus: true,
      subtitleLanguage: [
        'Arabic',
        'Chinese (China)',
        'French',
        'German',
        'Italian',
        'Korean',
        'Portuguese (Portugal)',
        'Russian',
        'Spanish',
        'Turkish',
        'Vietnamese'
      ],
      productDifficultyLevel: 'Beginner',
      audience: null,
      enrollments: 2249123,
      partners: [ 'University of Michigan' ],
      language: 'English',
      entityType: 'SPECIALIZATION',
      numProductRatings: 210975,
      allLanguageCodes: [
        'ar', 'zh', 'en',
        'fr', 'de', 'it',
        'ko', 'pt', 'ru',
        'es', 'tr', 'vi'
      ],
      avgProductRating: 4.811812774025358,
      skills: [
        'Computer Programming',
        'Data Structures',
        'Databases',
        'Python Programming',
        'Sql',
        'Application Programming Interfaces',
        'Json',
        'Sqlite',
        'Web',
        'Xml'
      ],
      imageUrl: 'https://d2j5ihb19pt1hq.cloudfront.net/sdp_page/s12n_logos/python.jpg',
      isCourseFree: false,
      objectUrl: '/specializations/python',
      objectID: 's12n~F-h1g0w7EeWeOApO_l5R1w',
      _snippetResult: { description: [Object] },
      _highlightResult: { name: [Object] }
    },
    {
      avgLearningHours: null,
      tagline: 'Build the Foundation for your Data Science career\nOffered by IBM',
      name: 'Data Science Fundamentals with Python and SQL',
      partnerLogos: [
        'http://coursera-university-assets.s3.amazonaws.com/bb/f5ced2bdd4437aa79f00eb1bf7fbf0/IBM-Logo-Blk---Square.png'
      ],
      isPartOfCourseraPlus: false,
      subtitleLanguage: [
        'Arabic',
        'Chinese (China)',
        'French',
        'German',
        'Italian',
        'Korean',
        'Persian',
        'Portuguese (Portugal)',
        'Russian',
        'Spanish',
        'Turkish',
        'Vietnamese'
      ],
      productDifficultyLevel: 'Beginner',
      audience: null,
      enrollments: 383465,
      partners: [ 'IBM' ],
      language: 'English',
      entityType: 'SPECIALIZATION',
      numProductRatings: 34062,
      allLanguageCodes: [
        'ar', 'zh', 'en',
        'fr', 'de', 'it',
        'ko', 'fa', 'pt',
        'ru', 'es', 'tr',
        'vi'
      ],
      avgProductRating: 4.565257471669307,
      skills: [
        'Computer Programming',
        'Databases',
        'General Statistics',
        'Numpy',
        'Python Programming',
        'Sql',
        'Ibm Db2',
        'Ipython',
        'Probability',
        'Rstudio'
      ],
      imageUrl: 'https://d15cw65ipctsrr.cloudfront.net/bd/0202c87e244d30bdecd889bd2719ae/DataScienceFundamentalsPythonSQL.png',
      isCourseFree: false,
      objectUrl: '/specializations/data-science-fundamentals-python-sql',
      objectID: 's12n~kuGzQBrlEeuKTA7v2iL8uQ',
      _snippetResult: { description: [Object] },
      _highlightResult: { name: [Object] }
    },
    {
      avgLearningHours: null,
      tagline: 'Get Ahead with Key Business Technologies\nOffered by IBM',
      name: 'Key Technologies for Business',
      partnerLogos: [
        'http://coursera-university-assets.s3.amazonaws.com/bb/f5ced2bdd4437aa79f00eb1bf7fbf0/IBM-Logo-Blk---Square.png'
      ],
      isPartOfCourseraPlus: false,
      subtitleLanguage: [
        'Arabic',
        'Chinese (China)',
        'French',
        'German',
        'Italian',
        'Korean',
        'Portuguese (Portugal)',
        'Russian',
        'Spanish',
        'Turkish',
        'Vietnamese'
      ],
      productDifficultyLevel: 'Beginner',
      audience: null,
      enrollments: 496486,
      partners: [ 'IBM' ],
      language: 'English',
      entityType: 'SPECIALIZATION',
      numProductRatings: 49340,
      allLanguageCodes: [
        'ar', 'zh', 'en',
        'fr', 'de', 'it',
        'ko', 'pt', 'ru',
        'es', 'tr', 'vi'
      ],
      avgProductRating: 4.685853263072557,
      skills: [
        'Artificial Neural Networks',
        'Cloud Computing',
        'Cloud Infrastructure',
        'Cloud Storage',
        'Data Mining',
        'Ibm Cloud',
        'Artificial General Intelligence',
        'Cloud Computing Security',
        'Ethics',
        'Ethics Of Artificial Intelligence'
      ],
      imageUrl: 'https://d15cw65ipctsrr.cloudfront.net/93/1543b8c7d64dad864ca79e876a065d/Key-Technology-Foundations-1-.png',
      isCourseFree: false,
      objectUrl: '/specializations/key-technologies-for-business',
      objectID: 's12n~mF13zqpxEeqDdgqb325wdw',
      _snippetResult: { description: [Object] },
      _highlightResult: { name: [Object] }
    },
    {
      avgLearningHours: null,
      tagline: '\nOffered by IBM',
      name: 'IBM AI Foundations for Business',
      partnerLogos: [
        'http://coursera-university-assets.s3.amazonaws.com/bb/f5ced2bdd4437aa79f00eb1bf7fbf0/IBM-Logo-Blk---Square.png'
      ],
      isPartOfCourseraPlus: false,
      subtitleLanguage: [
        'Arabic',
        'Chinese (China)',
        'French',
        'German',
        'Italian',
        'Korean',
        'Portuguese (Portugal)',
        'Russian',
        'Spanish',
        'Turkish',
        'Vietnamese'
      ],
      productDifficultyLevel: 'Beginner',
      audience: null,
      enrollments: 485730,
      partners: [ 'IBM' ],
      language: 'English',
      entityType: 'SPECIALIZATION',
      numProductRatings: 49076,
      allLanguageCodes: [
        'ar', 'zh', 'en',
        'fr', 'de', 'it',
        'ko', 'pt', 'ru',
        'es', 'tr', 'vi'
      ],
      avgProductRating: 4.685487814817833,
      skills: [
        'Artificial Neural Networks',
        'Business Solutions',
        'Data Mining',
        'Machine Learning',
        'Analysis',
        'Artificial General Intelligence',
        'Ethics',
        'Ethics Of Artificial Intelligence',
        'Information Architecture',
        'Laddering'
      ],
      imageUrl: 'https://d15cw65ipctsrr.cloudfront.net/bb/a0b5642d924caabb6101aa7e1afa66/IBM-AI-Foundations-for-Business.png',
      isCourseFree: false,
      objectUrl: '/specializations/ibm-ai-foundations-for-business',
      objectID: 's12n~zn_b0Y_lEeqE2Q5NANyNFw',
      _snippetResult: { description: [Object] },
      _highlightResult: { name: [Object] }
    },
    {
      avgLearningHours: null,
      tagline: 'Get ahead w/ Data Analysis & Visualization skills\nOffered by IBM',
      name: 'Data Analysis and Visualization Foundations',
      partnerLogos: [
        'http://coursera-university-assets.s3.amazonaws.com/bb/f5ced2bdd4437aa79f00eb1bf7fbf0/IBM-Logo-Blk---Square.png'
      ],
      isPartOfCourseraPlus: false,
      subtitleLanguage: [
        'Arabic',
        'Chinese (China)',
        'French',
        'German',
        'Italian',
        'Korean',
        'Portuguese (Portugal)',
        'Russian',
        'Spanish',
        'Turkish',
        'Vietnamese'
      ],
      productDifficultyLevel: 'Beginner',
      audience: null,
      enrollments: 35308,
      partners: [ 'IBM' ],
      language: 'English',
      entityType: 'SPECIALIZATION',
      numProductRatings: 1065,
      allLanguageCodes: [
        'ar', 'zh', 'en',
        'fr', 'de', 'it',
        'ko', 'pt', 'ru',
        'es', 'tr', 'vi'
      ],
      avgProductRating: 4.728169014084508,
      skills: [
        'Data Analysis',
        'Data Visualization',
        'Financial Analysis',
        'Microsoft Excel',
        'Pivot Table',
        'Sql',
        'Analysis',
        'Analytics',
        'Cleaning',
        'Software'
      ],
      imageUrl: 'https://d15cw65ipctsrr.cloudfront.net/6d/6fb8cc58064b8d85eae4cc5ed61448/Data-Analysis-Foundations-1200X1200.jpg',
      isCourseFree: false,
      objectUrl: '/specializations/data-analysis-visualization-foundations',
      objectID: 's12n~zjWaXRMhEeudwgrn4wF8EQ',
      _snippetResult: { description: [Object] },
      _highlightResult: { name: [Object] }
    },
    {
      avgLearningHours: null,
      tagline: 'Get hands-on skills for a career in data science\nOffered by IBM',
      name: 'Applied Data Science',
      partnerLogos: [
        'http://coursera-university-assets.s3.amazonaws.com/bb/f5ced2bdd4437aa79f00eb1bf7fbf0/IBM-Logo-Blk---Square.png'
      ],
      isPartOfCourseraPlus: false,
      subtitleLanguage: [
        'Arabic',
        'Chinese (China)',
        'French',
        'German',
        'Italian',
        'Korean',
        'Persian',
        'Portuguese (Portugal)',
        'Russian',
        'Spanish',
        'Turkish',
        'Vietnamese'
      ],
      productDifficultyLevel: 'Beginner',
      audience: null,
      enrollments: 334256,
      partners: [ 'IBM' ],
      language: 'English',
      entityType: 'SPECIALIZATION',
      numProductRatings: 27348,
      allLanguageCodes: [
        'ar', 'zh', 'en',
        'fr', 'de', 'it',
        'ko', 'fa', 'pt',
        'ru', 'es', 'tr',
        'vi'
      ],
      avgProductRating: 4.608728243381602,
      skills: [
        'Computer Programming',
        'Data Analysis',
        'Data Visualization',
        'Matplotlib',
        'Numpy',
        'Python Programming',
        'Regression',
        'Analysis',
        'Data Clustering Algorithms',
        'Modeling'
      ],
      imageUrl: 'https://d15cw65ipctsrr.cloudfront.net/8b/61b3208e9411e8bd0e199d89262fda/Applied_Data_Science.png',
      isCourseFree: false,
      objectUrl: '/specializations/applied-data-science',
      objectID: 's12n~gw6NIUimEeiedgp7b7p1Ig',
      _snippetResult: { description: [Object] },
      _highlightResult: { name: [Object] }
    },
    {
      avgLearningHours: 21,
      tagline: 'Offered by University of Alberta',
      name: 'Indigenous Canada',
      partnerLogos: [
        'https://coursera-university-assets.s3.amazonaws.com/35/23d929219e4489c2d11215009dc699/coursera_180x180.png'
      ],
      isPartOfCourseraPlus: true,
      subtitleLanguage: [
        'German',
        'Italian',
        'Russian',
        'Chinese (China)',
        'Korean',
        'Arabic',
        'Vietnamese',
        'French',
        'Portuguese (Portugal)',
        'Turkish',
        'Spanish'
      ],
      productDifficultyLevel: 'Mixed',
      audience: null,
      enrollments: 211503,
      partners: [ 'University of Alberta' ],
      language: 'English',
      entityType: 'COURSE',
      numProductRatings: 8299,
      allLanguageCodes: [
        'de', 'it', 'ru',
        'zh', 'ko', 'ar',
        'vi', 'fr', 'pt',
        'tr', 'es', 'en'
      ],
      avgProductRating: 4.81708639595132,
      skills: [
        'Art History',
        'Listening',
        'Empathy',
        'Human Learning',
        'Art',
        'Culture',
        'History',
        'Critical Thinking',
        'Awareness'
      ],
      imageUrl: 'https://s3.amazonaws.com/coursera-course-photos/35/01fcc0dd0011e6bfe6e9e792d574eb/Logo.png',
      isCourseFree: true,
      objectUrl: '/learn/indigenous-canada',
      objectID: 'course~jYd91UquEeWpQA4vMed_oQ',
      _snippetResult: { description: [Object] },
      _highlightResult: { name: [Object] }
    },
    {
      avgLearningHours: 16,
      tagline: 'Offered by Yale University',
      name: 'The Science of Well-Being',
      partnerLogos: [
        'https://coursera-university-assets.s3.amazonaws.com/b4/339da416653830d015f5a179f864e1/square_logo_large.png'
      ],
      isPartOfCourseraPlus: true,
      subtitleLanguage: [
        'Persian',
        'Russian',
        'Vietnamese',
        'Turkish',
        'Spanish',
        'Chinese (China)',
        'Portuguese (Brazil)',
        'Ukrainian',
        'German',
        'Italian',
        'Korean',
        'Arabic',
        'Portuguese (Portugal)',
        'French'
      ],
      productDifficultyLevel: 'Mixed',
      audience: null,
      enrollments: 3228917,
      partners: [ 'Yale University' ],
      language: 'English',
      entityType: 'COURSE',
      numProductRatings: 25271,
      allLanguageCodes: [
        'fa', 'ru', 'vi',
        'tr', 'es', 'zh',
        'pt', 'uk', 'de',
        'it', 'ko', 'ar',
        'fr', 'en'
      ],
      avgProductRating: 4.908076451268252,
      skills: [
        'Savoring',
        'Gratitude',
        'Positive Psychology',
        'Kindness',
        'Psychologies',
        'Exercise',
        'Happiness',
        'Habit',
        'Mindfulness',
        'Meditation'
      ],
      imageUrl: 'https://s3.amazonaws.com/coursera-course-photos/7e/aff5b0f54c11e7b5ae579a0e963c38/Logo_TheScienceofWell-Being.png',
      isCourseFree: true,
      objectUrl: '/learn/the-science-of-well-being',
      objectID: 'course~rUHfSakHEeeQ3gpuC4Fs_g',
      _snippetResult: { description: [Object] },
      _highlightResult: { name: [Object] }
    },
    {
      avgLearningHours: null,
      tagline: null,
      name: 'Cloud Architecture with Google Cloud',
      partnerLogos: [
        'http://coursera-university-assets.s3.amazonaws.com/4e/c2f4c0f4bb11e69a33576c875f4294/cloud-twitter-avatar.png'
      ],
      isPartOfCourseraPlus: true,
      subtitleLanguage: [
        'French',
        'German',
        'Japanese',
        'Portuguese (Brazil)',
        'Portuguese (Portugal)',
        'Russian',
        'Spanish'
      ],
      productDifficultyLevel: 'Intermediate',
      audience: null,
      enrollments: 488245,
      partners: [ 'Google Cloud' ],
      language: 'English',
      entityType: 'PROFESSIONAL CERTIFICATE',
      numProductRatings: 44727,
      allLanguageCodes: [
        'en', 'fr',
        'de', 'ja',
        'pt', 'ru',
        'es'
      ],
      avgProductRating: 4.702580097033114,
      skills: [
        'Cloud Computing',
        'Cloud Platforms',
        'Cloud Storage',
        'Google App Engine',
        'Google Cloud Platform',
        'Kubernetes',
        'Leadership And Management',
        'Identity Management',
        'Load Balancing',
        'Virtual Machine'
      ],
      imageUrl: 'https://d15cw65ipctsrr.cloudfront.net/1d/714104d1c241e8981bb58390da9811/Option-2_1.png',
      isCourseFree: false,
      objectUrl: '/professional-certificates/gcp-cloud-architect',
      objectID: 's12n~Zr7lPblmEemQRhI-rkeuOA',
      _snippetResult: { description: [Object] },
      _highlightResult: { name: [Object] }
    }
  ]